<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260611133516 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE registration_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, address TEXT NOT NULL, birth_date DATE NOT NULL, social_security_number VARCHAR(255) NOT NULL, fighter_nickname VARCHAR(255) NOT NULL, fighter_certification_number VARCHAR(255) NOT NULL, pokemon_starter VARCHAR(255) NOT NULL, email_address VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL, reviewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, review_note TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4470A1D9BF52BEC2 ON registration_requests (social_security_number)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4470A1D9C3E083CF ON registration_requests (fighter_certification_number)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE registration_requests');
    }
}
