<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260611143936 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE member_accounts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, display_number VARCHAR(255) NOT NULL, email_address VARCHAR(255) NOT NULL, password_hash VARCHAR(255) DEFAULT NULL, status VARCHAR(50) NOT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, password_set_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, registration_request_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3D153D467F45718C ON member_accounts (registration_request_id)');
        $this->addSql('CREATE TABLE validation_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(255) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consumed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, member_account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2E0C435570254153 ON validation_tokens (member_account_id)');
        $this->addSql('ALTER TABLE member_accounts ADD CONSTRAINT FK_3D153D467F45718C FOREIGN KEY (registration_request_id) REFERENCES registration_requests (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE validation_tokens ADD CONSTRAINT FK_2E0C435570254153 FOREIGN KEY (member_account_id) REFERENCES member_accounts (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE member_accounts DROP CONSTRAINT FK_3D153D467F45718C');
        $this->addSql('ALTER TABLE validation_tokens DROP CONSTRAINT FK_2E0C435570254153');
        $this->addSql('DROP TABLE member_accounts');
        $this->addSql('DROP TABLE validation_tokens');
    }
}
